### 矩阵变量-01
GET http://localhost:8080/demoController/matrixParams01/cars;color=red;year=2024
Accept: application/json

### 矩阵变量-02: 逗号分隔指定多个值
GET http://localhost:8080/demoController/matrixParams02/cars;colors=red,green,yellow;year=2022
Accept: application/json

### 矩阵变量-03: 重复变量名，指定多个值
GET http://localhost:8080/demoController/matrixParams02/cars;colors=red;colors=green;colors=yellow;year=2021
Accept: application/json

### 矩阵变量-04: 接收某一个路径段中的所有变量值
GET http://localhost:8080/demoController/matrixParams03/cars;colors=red;colors=green;colors=yellow;year=2025/users;name=Peter;arg=23
Accept: application/json

### 矩阵变量-05: 接收所有路径段中所有的值
GET http://localhost:8080/demoController/matrixParams04/cars;colors=red;colors=green;colors=yellow;year=2025/users;name=Peter;arg=23
Accept: application/json


### 查询参数01
GET http://localhost:8080/demoController/requestParam01?name=Peter
Accept: application/json

### 查询参数02: 查询参数，默认必须传，如果缺少就会报错
GET http://localhost:8080/demoController/requestParam01
Accept: application/json

### 查询参数03: 设置required=false
GET http://localhost:8080/demoController/requestParam02
Accept: application/json

### 查询参数04: 使用Optional 修改参数值
GET http://localhost:8080/demoController/requestParam03
Accept: application/json

### 查询参数05: 和map结合
GET http://localhost:8080/demoController/requestParam04?name=Peter&age=21
Accept: application/json

### 查询参数06: 和MultiValueMap结合
GET http://localhost:8080/demoController/requestParam05?name=Peter&name=Jone&age=22
Accept: application/json

